export const API_PREFIX = '/api';
export const API_VERSION = 'v1';
export const API_BASE_PATH = `${API_PREFIX}/${API_VERSION}`;

const withBase = (path: string) => `${API_BASE_PATH}${path}`;

export const apiEndpoints = {
  auth: {
    login: withBase('/auth/login'),
    logout: withBase('/auth/logout'),
    me: withBase('/auth/me'),
  },
  users: {
    create: withBase('/users'),
    list: withBase('/users'),
    get: withBase('/users/:id'),
    update: withBase('/users/:id'),
    delete: withBase('/users/:id'),
  },
  userInvite: {
    invite: withBase('/users/invite'),
    list: withBase('/users/invite'),
    resetPassword: withBase('/users/:id/reset-password'),
    pending: withBase('/users/invite/pending'),
  },
  userActivate: {
    activate: withBase('/users/activate'),
  },
  departments: {
    create: withBase('/departments'),
    list: withBase('/departments'),
    get: withBase('/departments/:id'),
    update: withBase('/departments/:id'),
    delete: withBase('/departments/:id'),
  },
  media: {
    presignUpload: withBase('/media/presign-upload'),
    uploadSessions: withBase('/media/uploads'),
    uploadSession: withBase('/media/uploads/:sessionId'),
    uploadSessionParts: withBase('/media/uploads/:sessionId/parts/presign'),
    uploadSessionComplete: withBase('/media/uploads/:sessionId/complete'),
    create: withBase('/media'),
    list: withBase('/media'),
    get: withBase('/media/:id'),
    delete: withBase('/media/:id'),
    complete: withBase('/media/:id/complete'),
  },
  presentations: {
    create: withBase('/presentations'),
    list: withBase('/presentations'),
    get: withBase('/presentations/:id'),
    update: withBase('/presentations/:id'),
    delete: withBase('/presentations/:id'),
    items: withBase('/presentations/:id/items'),
    item: withBase('/presentations/:id/items/:itemId'),
    slotItems: withBase('/presentations/:id/slots'),
    slotItem: withBase('/presentations/:id/slots/:slotItemId'),
  },
  schedules: {
    create: withBase('/schedules'),
    list: withBase('/schedules'),
    get: withBase('/schedules/:id'),
    update: withBase('/schedules/:id'),
    publish: withBase('/schedules/:id/publish'),
    publishes: withBase('/schedules/:id/publishes'),
    updatePublishTarget: withBase('/publishes/:publishId/targets/:targetId'),
    publishStatus: withBase('/publishes/:id'),
    takeDownPublish: withBase('/publishes/:id/take-down'),
    items: withBase('/schedules/:id/items'),
    item: withBase('/schedules/:id/items/:itemId'),
  },
  scheduleRequests: {
    create: withBase('/schedule-requests'),
    list: withBase('/schedule-requests'),
    get: withBase('/schedule-requests/:id'),
    update: withBase('/schedule-requests/:id'),
    approve: withBase('/schedule-requests/:id/approve'),
    reject: withBase('/schedule-requests/:id/reject'),
    cancel: withBase('/schedule-requests/:id/cancel'),
    takeDown: withBase('/schedule-requests/:id/take-down'),
    publish: withBase('/schedule-requests/:id/publish'),
    statusSummary: withBase('/schedule-requests/status-summary'),
  },
  scheduleReservations: {
    preview: withBase('/schedule-reservations/preview'),
  },
  screens: {
    create: withBase('/screens'),
    list: withBase('/screens'),
    summary: withBase('/screens/summary'),
    aspectRatios: withBase('/screens/aspect-ratios'),
    overview: withBase('/screens/overview'),
    scheduleTimeline: withBase('/screens/schedule-timeline'),
    get: withBase('/screens/:id'),
    defaultMedia: withBase('/screens/:id/default-media'),
    update: withBase('/screens/:id'),
    delete: withBase('/screens/:id'),
    status: withBase('/screens/:id/status'),
    heartbeats: withBase('/screens/:id/heartbeats'),
    screenshotSettings: withBase('/screens/:id/screenshot-settings'),
    screenshot: withBase('/screens/:id/screenshot'),
    nowPlaying: withBase('/screens/:id/now-playing'),
	    availability: withBase('/screens/:id/availability'),
	    snapshot: withBase('/screens/:id/snapshot'),
	    recentCommands: withBase('/screens/:id/commands/recent'),
	    deliveryStatus: withBase('/screens/:id/delivery-status'),
	    mediaCacheReports: withBase('/screens/:id/media-cache-reports/recent'),
	  },
  screenGroups: {
    create: withBase('/screen-groups'),
    list: withBase('/screen-groups'),
    availableScreens: withBase('/screen-groups/available-screens'),
    get: withBase('/screen-groups/:id'),
    availability: withBase('/screen-groups/:id/availability'),
    snapshot: withBase('/screen-groups/:id/snapshot'),
    screenshotSettings: withBase('/screen-groups/:id/screenshot-settings'),
    screenshot: withBase('/screen-groups/:id/screenshot'),
    update: withBase('/screen-groups/:id'),
    delete: withBase('/screen-groups/:id'),
  },
  layouts: {
    create: withBase('/layouts'),
    list: withBase('/layouts'),
    get: withBase('/layouts/:id'),
    update: withBase('/layouts/:id'),
    delete: withBase('/layouts/:id'),
  },
  requests: {
    create: withBase('/requests'),
    list: withBase('/requests'),
    get: withBase('/requests/:id'),
    update: withBase('/requests/:id'),
    addMessage: withBase('/requests/:id/messages'),
    listMessages: withBase('/requests/:id/messages'),
  },
  notifications: {
    list: withBase('/notifications'),
    unreadCount: withBase('/notifications/unread-count'),
    get: withBase('/notifications/:id'),
    markRead: withBase('/notifications/:id/read'),
    markAllRead: withBase('/notifications/read-all'),
    delete: withBase('/notifications/:id'),
  },
  auditLogs: {
    list: withBase('/audit-logs'),
    get: withBase('/audit-logs/:id'),
    export: withBase('/audit-logs/export'),
  },
  apiKeys: {
    create: withBase('/api-keys'),
    list: withBase('/api-keys'),
    rotate: withBase('/api-keys/:id/rotate'),
    revoke: withBase('/api-keys/:id/revoke'),
  },
  deviceTelemetry: {
    heartbeat: withBase('/device/heartbeat'),
    proofOfPlay: withBase('/device/proof-of-play'),
    screenshot: withBase('/device/screenshot'),
    screenshotPolicy: withBase('/device/:deviceId/screenshot-policy'),
    pairingStatus: withBase('/device/:deviceId/pairing-status'),
    commands: withBase('/device/:deviceId/commands'),
    ackCommand: withBase('/device/:deviceId/commands/:commandId/ack'),
    desiredState: withBase('/device/:deviceId/desired-state'),
    snapshot: withBase('/device/:deviceId/snapshot'),
    defaultMedia: withBase('/device/:deviceId/default-media'),
    mediaCacheReport: withBase('/device/:deviceId/media-cache-report'),
  },
  devicePairing: {
    generate: withBase('/device-pairing/generate'),
    complete: withBase('/device-pairing/complete'),
    list: withBase('/device-pairing'),
    orphans: withBase('/device-pairing/orphans'),
    revoke: withBase('/device-pairing/:deviceId/revoke'),
    request: withBase('/device-pairing/request'),
    status: withBase('/device-pairing/status'),
    confirm: withBase('/device-pairing/confirm'),
    recovery: withBase('/device-pairing/recovery/:deviceId'),
    startRecovery: withBase('/device-pairing/recovery/:deviceId'),
  },
  emergency: {
    trigger: withBase('/emergency/trigger'),
    status: withBase('/emergency/status'),
    clear: withBase('/emergency/:id/clear'),
    history: withBase('/emergency/history'),
  },
  emergencyTypes: {
    create: withBase('/emergency-types'),
    list: withBase('/emergency-types'),
    get: withBase('/emergency-types/:id'),
    update: withBase('/emergency-types/:id'),
    delete: withBase('/emergency-types/:id'),
  },
  webhooks: {
    create: withBase('/webhooks'),
    list: withBase('/webhooks'),
    update: withBase('/webhooks/:id'),
    delete: withBase('/webhooks/:id'),
    test: withBase('/webhooks/:id/test'),
  },
  ssoConfig: {
    upsert: withBase('/sso-config'),
    list: withBase('/sso-config'),
    deactivate: withBase('/sso-config/:id/deactivate'),
  },
  settings: {
    list: withBase('/settings'),
    upsert: withBase('/settings'),
    general: withBase('/settings/general'),
    branding: withBase('/settings/branding'),
    security: withBase('/settings/security'),
    appearance: withBase('/settings/appearance'),
    backups: withBase('/settings/backups'),
    backupById: withBase('/settings/backups/:id'),
    backupRun: withBase('/settings/backups/run'),
    backupHistory: withBase('/settings/backups/history'),
    logs: withBase('/settings/logs'),
    defaultMedia: withBase('/settings/default-media'),
    defaultMediaVariants: withBase('/settings/default-media/variants'),
    defaultMediaTargets: withBase('/settings/default-media/targets'),
  },
  conversations: {
    start: withBase('/conversations'),
    list: withBase('/conversations'),
    listMessages: withBase('/conversations/:id/messages'),
    sendMessage: withBase('/conversations/:id/messages'),
    markRead: withBase('/conversations/:id/read'),
  },
  chat: {
    createDm: withBase('/chat/dm'),
    createConversation: withBase('/chat/conversations'),
    listConversations: withBase('/chat/conversations'),
    getConversation: withBase('/chat/conversations/:id'),
    shareLink: withBase('/chat/conversations/:id/share-link'),
    updateConversation: withBase('/chat/conversations/:id'),
    archiveConversation: withBase('/chat/conversations/:id/archive'),
    unarchiveConversation: withBase('/chat/conversations/:id/unarchive'),
    hardDeleteConversation: withBase('/chat/conversations/:id'),
    inviteMembers: withBase('/chat/conversations/:id/invite'),
    removeMember: withBase('/chat/conversations/:id/members/remove'),
    listMessages: withBase('/chat/conversations/:id/messages'),
    listThread: withBase('/chat/conversations/:id/thread/:parentMessageId'),
    sendMessage: withBase('/chat/conversations/:id/messages'),
    editMessage: withBase('/chat/messages/:id'),
    deleteMessage: withBase('/chat/messages/:id'),
    reactToMessage: withBase('/chat/messages/:id/reactions'),
    pinMessage: withBase('/chat/messages/:id/pin'),
    unpinMessage: withBase('/chat/messages/:id/unpin'),
    markRead: withBase('/chat/conversations/:id/read'),
    moderateConversation: withBase('/chat/conversations/:id/moderation'),
    listPins: withBase('/chat/conversations/:id/pins'),
    createBookmark: withBase('/chat/conversations/:id/bookmarks'),
    listBookmarks: withBase('/chat/conversations/:id/bookmarks'),
    deleteBookmark: withBase('/chat/bookmarks/:id'),
  },
  proofOfPlay: {
    list: withBase('/proof-of-play'),
    export: withBase('/proof-of-play/export'),
  },
  metrics: {
    overview: withBase('/metrics/overview'),
  },
  observability: {
    overview: withBase('/observability/overview'),
    machines: withBase('/observability/machines'),
    screen: withBase('/observability/screens/:id'),
  },
  reports: {
    summary: withBase('/reports/summary'),
    schedules: withBase('/reports/schedules'),
    trends: withBase('/reports/trends'),
    requestsByDepartment: withBase('/reports/requests-by-department'),
    offlineScreens: withBase('/reports/offline-screens'),
    storage: withBase('/reports/storage'),
    systemHealth: withBase('/reports/system-health'),
    export: withBase('/reports/export'),
  },
  security: {
    clientEvents: withBase('/security/client-events'),
  },
  roles: {
    create: withBase('/roles'),
    list: withBase('/roles'),
    get: withBase('/roles/:id'),
    update: withBase('/roles/:id'),
    delete: withBase('/roles/:id'),
  },
  permissions: {
    metadata: withBase('/permissions/metadata'),
  },
  screenGroupNowPlaying: {
    get: withBase('/screen-groups/:id/now-playing'),
  },
};

export const PENDINGSTATUS = 'PENDING';
