export const API_BASE_PATH = "/api/v1";

export const endpoints = {
  apiKeys: {
    base: "/api-keys",
    rotate: (apiKeyId: string) => `/api-keys/${apiKeyId}/rotate`,
    revoke: (apiKeyId: string) => `/api-keys/${apiKeyId}/revoke`,
  },
  auditLogs: {
    base: "/audit-logs",
    byId: (auditLogId: string) => `/audit-logs/${auditLogId}`,
    export: "/audit-logs/export",
  },
  auth: {
    login: "/auth/login",
    me: "/auth/me",
    logout: "/auth/logout",
  },
  conversations: {
    base: "/conversations",
    messages: (conversationId: string) => `/conversations/${conversationId}/messages`,
    markRead: (conversationId: string) => `/conversations/${conversationId}/read`,
  },
  chat: {
    dm: "/chat/dm",
    conversations: "/chat/conversations",
    conversationById: (conversationId: string) => `/chat/conversations/${conversationId}`,
    messages: (conversationId: string) => `/chat/conversations/${conversationId}/messages`,
    thread: (conversationId: string, parentMessageId: string) =>
      `/chat/conversations/${conversationId}/thread/${parentMessageId}`,
    shareLink: (conversationId: string) => `/chat/conversations/${conversationId}/share-link`,
    listPins: (conversationId: string) => `/chat/conversations/${conversationId}/pins`,
    createBookmark: (conversationId: string) => `/chat/conversations/${conversationId}/bookmarks`,
    listBookmarks: (conversationId: string) => `/chat/conversations/${conversationId}/bookmarks`,
    read: (conversationId: string) => `/chat/conversations/${conversationId}/read`,
    invite: (conversationId: string) => `/chat/conversations/${conversationId}/invite`,
    removeMember: (conversationId: string) => `/chat/conversations/${conversationId}/members/remove`,
    updateConversation: (conversationId: string) => `/chat/conversations/${conversationId}`,
    archiveConversation: (conversationId: string) => `/chat/conversations/${conversationId}/archive`,
    unarchiveConversation: (conversationId: string) => `/chat/conversations/${conversationId}/unarchive`,
    deleteConversation: (conversationId: string) => `/chat/conversations/${conversationId}`,
    moderateConversation: (conversationId: string) => `/chat/conversations/${conversationId}/moderation`,
    messageById: (messageId: string) => `/chat/messages/${messageId}`,
    reactions: (messageId: string) => `/chat/messages/${messageId}/reactions`,
    pinMessage: (messageId: string) => `/chat/messages/${messageId}/pin`,
    unpinMessage: (messageId: string) => `/chat/messages/${messageId}/unpin`,
    deleteBookmark: (bookmarkId: string) => `/chat/bookmarks/${bookmarkId}`,
  },
  departments: {
    base: "/departments",
    byId: (departmentId: string) => `/departments/${departmentId}`,
  },
  devicePairing: {
    base: "/device-pairing",
    generate: "/device-pairing/generate",
    complete: "/device-pairing/complete",
    status: "/device-pairing/status",
    orphans: "/device-pairing/orphans",
    revoke: (deviceId: string) => `/device-pairing/${deviceId}/revoke`,
    recovery: (deviceId: string) => `/device-pairing/recovery/${deviceId}`,
  },
  deviceTelemetry: {
    heartbeat: "/device/heartbeat",
    proofOfPlay: "/device/proof-of-play",
    screenshot: "/device/screenshot",
    commands: (deviceId: string) => `/device/${deviceId}/commands`,
    ackCommand: (deviceId: string, commandId: string) =>
      `/device/${deviceId}/commands/${commandId}/ack`,
  },
  emergency: {
    trigger: "/emergency/trigger",
    status: "/emergency/status",
    clear: (emergencyId: string) => `/emergency/${emergencyId}/clear`,
    history: "/emergency/history",
  },
  health: {
    base: "/health",
  },
  media: {
    base: "/media",
    presignUpload: "/media/presign-upload",
    uploadSessions: "/media/uploads",
    uploadSession: (sessionId: string) => `/media/uploads/${sessionId}`,
    uploadSessionParts: (sessionId: string) => `/media/uploads/${sessionId}/parts/presign`,
    uploadSessionComplete: (sessionId: string) => `/media/uploads/${sessionId}/complete`,
    complete: (mediaId: string) => `/media/${mediaId}/complete`,
    byId: (mediaId: string) => `/media/${mediaId}`,
  },
  metrics: {
    overview: "/metrics/overview",
  },
  observability: {
    overview: "/observability/overview",
    screen: (screenId: string) => `/observability/screens/${screenId}`,
  },
  notifications: {
    base: "/notifications",
    unreadCount: "/notifications/unread-count",
    byId: (notificationId: string) => `/notifications/${notificationId}`,
    markRead: (notificationId: string) => `/notifications/${notificationId}/read`,
    markAllRead: "/notifications/read-all",
  },
  permissions: {
    metadata: "/permissions/metadata",
  },
  layouts: {
    base: "/layouts",
    byId: (layoutId: string) => `/layouts/${layoutId}`,
  },
  presentations: {
    base: "/presentations",
    byId: (presentationId: string) => `/presentations/${presentationId}`,
    slots: (presentationId: string) => `/presentations/${presentationId}/slots`,
  },
  proofOfPlay: {
    base: "/proof-of-play",
    export: "/proof-of-play/export",
  },
  reports: {
    summary: "/reports/summary",
    schedules: "/reports/schedules",
    trends: "/reports/trends",
    requestsByDepartment: "/reports/requests-by-department",
    offlineScreens: "/reports/offline-screens",
    storage: "/reports/storage",
    systemHealth: "/reports/system-health",
    export: "/reports/export",
  },
  requests: {
    base: "/requests",
    byId: (requestId: string) => `/requests/${requestId}`,
    messages: (requestId: string) => `/requests/${requestId}/messages`,
  },
  roles: {
    base: "/roles",
    byId: (roleId: string) => `/roles/${roleId}`,
  },
  schedules: {
    base: "/schedules",
    byId: (scheduleId: string) => `/schedules/${scheduleId}`,
    publish: (scheduleId: string) => `/schedules/${scheduleId}/publish`,
    items: (scheduleId: string) => `/schedules/${scheduleId}/items`,
    publishById: (publishId: string) => `/publishes/${publishId}`,
    takeDownPublish: (publishId: string) => `/publishes/${publishId}/take-down`,
    publishesForSchedule: (scheduleId: string) => `/schedules/${scheduleId}/publishes`,
    publishTarget: (publishId: string, targetId: string) => `/publishes/${publishId}/targets/${targetId}`,
  },
  scheduleRequests: {
    base: "/schedule-requests",
    statusSummary: "/schedule-requests/status-summary",
    approve: (requestId: string) => `/schedule-requests/${requestId}/approve`,
    publish: (requestId: string) => `/schedule-requests/${requestId}/publish`,
    reject: (requestId: string) => `/schedule-requests/${requestId}/reject`,
    cancel: (requestId: string) => `/schedule-requests/${requestId}/cancel`,
    takeDown: (requestId: string) => `/schedule-requests/${requestId}/take-down`,
  },
  scheduleReservations: {
    preview: "/schedule-reservations/preview",
  },
  screens: {
    base: "/screens",
    summary: "/screens/summary",
    byId: (screenId: string) => `/screens/${screenId}`,
    overview: "/screens/overview",
    scheduleTimeline: "/screens/schedule-timeline",
    nowPlaying: (screenId: string) => `/screens/${screenId}/now-playing`,
    status: (screenId: string) => `/screens/${screenId}/status`,
    availability: (screenId: string) => `/screens/${screenId}/availability`,
    snapshot: (screenId: string) => `/screens/${screenId}/snapshot`,
    recentCommands: (screenId: string) => `/screens/${screenId}/commands/recent`,
    deliveryStatus: (screenId: string) => `/screens/${screenId}/delivery-status`,
    mediaCacheReports: (screenId: string) => `/screens/${screenId}/media-cache-reports/recent`,
    screenshot: (screenId: string) => `/screens/${screenId}/screenshot`,
    groups: "/screen-groups",
    groupById: (groupId: string) => `/screen-groups/${groupId}`,
    aspectRatios: "/screens/aspect-ratios",
  },
  screenGroups: {
    snapshot: (groupId: string) => `/screen-groups/${groupId}/snapshot`,
  },
  security: {
    clientEvents: "/security/client-events",
  },
  settings: {
    base: "/settings",
    general: "/settings/general",
    branding: "/settings/branding",
    security: "/settings/security",
    appearance: "/settings/appearance",
    backups: "/settings/backups",
    backupById: (backupId: string) => `/settings/backups/${backupId}`,
    backupRun: "/settings/backups/run",
    backupHistory: "/settings/backups/history",
    logs: "/settings/logs",
    defaultMedia: "/settings/default-media",
    defaultMediaVariants: "/settings/default-media/variants",
    defaultMediaTargets: "/settings/default-media/targets",
  },
  ssoConfig: {
    base: "/sso-config",
    deactivate: (id: string) => `/sso-config/${id}/deactivate`,
  },
  users: {
    base: "/users",
    invite: "/users/invite",
    activate: "/users/activate",
    resetPassword: (userId: string) => `/users/${userId}/reset-password`,
    byId: (userId: string) => `/users/${userId}`,
  },
  webhooks: {
    base: "/webhooks",
    byId: (webhookId: string) => `/webhooks/${webhookId}`,
    test: (webhookId: string) => `/webhooks/${webhookId}/test`,
  },
} as const;
